services:
  pmi-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://148.230.100.61/api
    container_name: pmi-fe-app
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - pmi-network
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  pmi-network:
    external: true
    name: pmi-be-call-master_pmi-network
