services:
  # ============================================
  # FRONTEND - Next.js
  # ============================================
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://api.pmikotasmg.site/api
        - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-}
    container_name: pmi-fe-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - pmi-network

networks:
  pmi-network:
    external: true
    name: pmi-be-call-master_pmi-network
